name: ndx2

services:
  ndx:
    build:
      context: .
      dockerfile: apps/ndx/docker/Dockerfile
    image: ndx2-ndx:latest
    container_name: ndx
    env_file:
      - apps/ndx/docker/.env
    ports:
      - "${NDX_WEB_HOST_PORT:-18082}:18080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./volume:/ndx
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NDX_ROOT=/ndx
      - NDX_HOST_ROOT=F:/dev/ndx2/volume
