export {
  defaultServerVolumeMap,
  NDX_CONTAINER_ASSETS_ROOT,
  NDX_CONTAINER_DATA_ROOT,
  NDX_CONTAINER_LOG_ROOT,
  NDX_CONTAINER_NDX_HOME,
  NDX_CONTAINER_ROOT,
  NDX_CONTAINER_USER_HOME,
  NDX_CONTAINER_WORKSPACE,
  serverContainerNdxHome,
  serverContainerRoot,
  serverHostWorkspace,
  serverPathRelativeToWorkspace,
  serverContainerUserHome,
  serverContainerWorkspace,
  toServerContainerPath,
  toHostWorkspacePath,
  toServerProjectPath,
  toServerUserHome,
  toServerWorkspaceDescendantPath,
  toServerWorkspacePath,
  normalizeWorkspaceProjectName,
  serverWorkspaceProjectPath,
  workspaceProjectNameFromPath,
  type ServerVolumeMap
} from "./pathMapping.js";
