export const webclientDomain = Object.freeze({
  surface: "webclient",
  runtime: "common"
});

export {
  DEFAULT_NDX_WEB_CLIENT_LOCALE,
  createInitialWebClientState,
  isAbsoluteProjectPath,
  isNDXWebClientLocale,
  makeLocalProject,
  normalizeWebClientState
} from "../server/client-state/state.js";
export type {
  NDXWebClientLocale,
  NDXWebClientProject,
  NDXWebClientSession,
  NDXWebClientStateDocument
} from "../server/client-state/types.js";
export { NDX_AGENT_WEB_API, sessionDataToSessionEvent } from "./protocol/index.js";
export type {
  NDXAgentWebAppendSessionMessageRequest,
  NDXAgentWebClientStateResponse,
  NDXAgentWebContextUsage,
  NDXAgentWebContextUsagePart,
  NDXAgentModelFolderPatchDraftRequest,
  NDXAgentModelFolderPatchDraftResponse,
  NDXAgentModelFolderPatchManifest,
  NDXAgentModelFolderPatchRequest,
  NDXAgentModelFolderPatchResponse,
  NDXAgentWebCreateModelRequest,
  NDXAgentWebCreateChatFolderRequest,
  NDXAgentWebCreateChatSessionRequest,
  NDXAgentWebEmbeddingSettings,
  NDXAgentWebEmbeddingSettingsResponse,
  NDXAgentWebCreateProjectRequest,
  NDXAgentWebCreateProviderRequest,
  NDXAgentWebCreateSessionRequest,
  NDXAgentWebErrorResponse,
  NDXAgentWebMetadataResponse,
  NDXAgentWebModel,
  NDXAgentWebModelConfig,
  NDXAgentWebModelsResponse,
  NDXReasoningEffort,
  NDXAgentWebProject,
  NDXAgentWebProjectsResponse,
  NDXAgentWebChatFolder,
  NDXAgentWebChatFoldersResponse,
  NDXAgentWebChatSession,
  NDXAgentWebChatSessionsResponse,
  NDXAgentWebProvider,
  NDXAgentWebProvidersResponse,
  NDXAgentWebSession,
  NDXAgentWebSessionData,
  NDXAgentWebSessionDataResponse,
  NDXAgentWebSessionMessageResponse,
  NDXAgentWebSessionMetadata,
  NDXAgentWebSettingsDocument,
  NDXAgentWebSettingsResponse,
  NDXAgentWebSessionsResponse,
  NDXAgentWebRunSelfcheckRequest,
  NDXAgentWebRunSelfcheckResponse,
  NDXAgentWebSelfcheck,
  NDXAgentWebSelfcheckCandidate,
  NDXAgentWebSelfcheckCandidatesResponse,
  NDXAgentWebSelfcheckCursor,
  NDXAgentWebSelfcheckCursorsResponse,
  NDXAgentWebSelfcheckDetailResponse,
  NDXAgentWebSelfcheckResponse,
  NDXAgentWebSelfcheckRun,
  NDXAgentWebSelfcheckRunsResponse,
  NDXAgentWebSelfcheckStatus,
  NDXAgentWebSelfcheckSubjectKind,
  NDXAgentWebUpdateClientStateRequest,
  NDXAgentWebUpdateSelfcheckRequest,
  NDXAgentWebUpdateChatFolderRequest,
  NDXAgentWebUpdateChatSessionRequest,
  NDXAgentWebUpdateEmbeddingSettingsRequest,
  NDXAgentWebUpdateModelRequest,
  NDXAgentWebUpdateProviderRequest,
  NDXAgentWebUpdateSettingsRequest,
  NDXAgentWebWorkspaceDirectoriesResponse,
  NDXAgentWebWorkspaceDirectory,
  NDXAgentWebWorkspaceMetadata
} from "./protocol/index.js";
