export enum RSC {
  APP_STATUS_NO_ACTIVE_PROJECT_ALERT = "app.status.noActiveProject.alert",
  SESSION_COMPOSER_IDLE_STATUS = "session.composer.idle.status",
  SESSION_COMPOSER_ATTACH_BUTTON = "session.composer.attach.button",
  SESSION_COMPOSER_ATTACH_IMAGE_BUTTON = "session.composer.attachImage.button",
  SESSION_COMPOSER_ATTACHMENT_IMAGE_ONLY_STATUS = "session.composer.attachment.imageOnly.status",
  SESSION_COMPOSER_ATTACHMENT_FILE_ONLY_STATUS = "session.composer.attachment.fileOnly.status",
  SESSION_COMPOSER_ATTACHMENT_UNSUPPORTED_STATUS = "session.composer.attachment.unsupported.status",
  SESSION_COMPOSER_INPUT_LABEL = "session.composer.input.label",
  SESSION_COMPOSER_INTERRUPT_BUTTON = "session.composer.interrupt.button",
  SESSION_COMPOSER_INTERRUPT_PENDING_STATUS = "session.composer.interrupt.pending.status",
  SESSION_COMPOSER_MODEL_CHOOSE_BUTTON = "session.composer.model.choose.button",
  SESSION_COMPOSER_REQUEST_PENDING_STATUS = "session.composer.request.pending.status",
  SESSION_COMPOSER_RUNNING_STATUS = "session.composer.running.status",
  SESSION_COMPOSER_SEND_BUTTON = "session.composer.send.button",
  SESSION_CONTEXT_USAGE_LABEL = "session.contextUsage.label",
  SESSION_CONTEXT_USAGE_PART_DEVELOPER_LABEL = "session.contextUsage.part.developer.label",
  SESSION_CONTEXT_USAGE_PART_HISTORY_LABEL = "session.contextUsage.part.history.label",
  SESSION_CONTEXT_USAGE_PART_REMAINING_LABEL = "session.contextUsage.part.remaining.label",
  SESSION_CONTEXT_USAGE_PART_TOOL_DEFINITIONS_LABEL = "session.contextUsage.part.toolDefinitions.label",
  SESSION_CONTEXT_USAGE_PART_USER_LABEL = "session.contextUsage.part.user.label",
  SESSION_CONTEXT_USAGE_POPOVER_TITLE_TEXT = "session.contextUsage.popover.title.text",
  SESSION_MODEL_DIALOG_BUSY_STATUS = "session.model.dialog.busy.status",
  SESSION_MODEL_DIALOG_CLOSE_BUTTON = "session.model.dialog.close.button",
  SESSION_MODEL_DIALOG_FAILED_ALERT = "session.model.dialog.failed.alert",
  SESSION_MODEL_DIALOG_MODEL_ADD_BUTTON = "session.model.dialog.model.add.button",
  SESSION_MODEL_DIALOG_MODEL_CONTEXT_SIZE_INPUT_PLACEHOLDER = "session.model.dialog.model.contextSize.input.placeholder",
  SESSION_MODEL_DIALOG_MODEL_DELETE_BUTTON = "session.model.dialog.model.delete.button",
  SESSION_MODEL_DIALOG_MODEL_EDIT_BUTTON = "session.model.dialog.model.edit.button",
  SESSION_MODEL_DIALOG_MODEL_EMPTY_MESSAGE = "session.model.dialog.model.empty.message",
  SESSION_MODEL_DIALOG_MODEL_NAME_INPUT_PLACEHOLDER = "session.model.dialog.model.name.input.placeholder",
  SESSION_MODEL_DIALOG_MODEL_REFRESH_BUTTON = "session.model.dialog.model.refresh.button",
  SESSION_MODEL_DIALOG_MODEL_REQUIRED_ALERT = "session.model.dialog.model.required.alert",
  SESSION_MODEL_DIALOG_MODEL_SAVE_BUTTON = "session.model.dialog.model.save.button",
  SESSION_MODEL_DIALOG_MODEL_SYNC_FAILED_ALERT = "session.model.dialog.model.syncFailed.alert",
  SESSION_MODEL_DIALOG_PROVIDER_ADD_BUTTON = "session.model.dialog.provider.add.button",
  SESSION_MODEL_DIALOG_PROVIDER_DELETE_BUTTON = "session.model.dialog.provider.delete.button",
  SESSION_MODEL_DIALOG_PROVIDER_REQUIRED_ALERT = "session.model.dialog.provider.required.alert",
  SESSION_MODEL_DIALOG_PROVIDER_TITLE_INPUT_PLACEHOLDER = "session.model.dialog.provider.title.input.placeholder",
  SESSION_MODEL_DIALOG_PROVIDER_TOKEN_INPUT_PLACEHOLDER = "session.model.dialog.provider.token.input.placeholder",
  SESSION_MODEL_DIALOG_PROVIDER_URL_INPUT_PLACEHOLDER = "session.model.dialog.provider.url.input.placeholder",
  SESSION_MODEL_DIALOG_TITLE_TEXT = "session.model.dialog.title.text",
  SESSION_SOCKET_ERROR_ALERT = "session.socket.error.alert",
  SESSION_SOCKET_NEGOTIATED_PROJECT_LABEL = "session.socket.negotiatedProject.label",
  SESSION_SOCKET_OFFLINE_ALERT = "session.socket.offline.alert",
}

export const CONTEXT_USAGE_PART_RSC: Record<string, RSC> = {
  developer: RSC.SESSION_CONTEXT_USAGE_PART_DEVELOPER_LABEL,
  history: RSC.SESSION_CONTEXT_USAGE_PART_HISTORY_LABEL,
  remaining: RSC.SESSION_CONTEXT_USAGE_PART_REMAINING_LABEL,
  toolDefinitions: RSC.SESSION_CONTEXT_USAGE_PART_TOOL_DEFINITIONS_LABEL,
  user: RSC.SESSION_CONTEXT_USAGE_PART_USER_LABEL
};
