export enum RSC {
  PROJECT_SESSION_RENAME_DIALOG_CANCEL_BUTTON = "project.session.rename.dialog.cancel.button",
  PROJECT_SESSION_RENAME_DIALOG_PENDING_STATUS = "project.session.rename.dialog.pending.status",
  PROJECT_SESSION_RENAME_DIALOG_SUBMIT_BUTTON = "project.session.rename.dialog.submit.button",
  PROJECT_SESSION_RENAME_DIALOG_TITLE_INPUT_LABEL = "project.session.rename.dialog.title.input.label",
  PROJECT_SESSION_RENAME_DIALOG_TITLE_TEXT = "project.session.rename.dialog.title.text",
  PROJECT_SIDEBAR_CHATS_TITLE_TEXT = "project.sidebar.chats.title.text",
  PROJECT_SIDEBAR_PROJECT_DELETE_BUTTON = "project.sidebar.project.delete.button",
  PROJECT_SIDEBAR_PROJECT_NEW_SESSION_BUTTON = "project.sidebar.project.newSession.button",
  PROJECT_SIDEBAR_PROJECT_OPEN_VSCODE_BUTTON = "project.sidebar.project.openVSCode.button",
  PROJECT_SIDEBAR_PROJECTS_ADD_BUTTON = "project.sidebar.projects.add.button",
  PROJECT_SIDEBAR_PROJECTS_EMPTY_MESSAGE = "project.sidebar.projects.empty.message",
  PROJECT_SIDEBAR_PROJECTS_SELECTED_LIST_LABEL = "project.sidebar.projects.selectedList.label",
  PROJECT_SIDEBAR_PROJECTS_TITLE_TEXT = "project.sidebar.projects.title.text",
  PROJECT_SIDEBAR_SESSION_DELETE_BUTTON = "project.sidebar.session.delete.button",
  PROJECT_SIDEBAR_SESSION_RENAME_BUTTON = "project.sidebar.session.rename.button",
  PROJECT_SIDEBAR_SESSIONS_COLLAPSE_BUTTON = "project.sidebar.sessions.collapse.button",
  PROJECT_SIDEBAR_SESSIONS_SHOW_MORE_BUTTON = "project.sidebar.sessions.showMore.button",
}
